from fastapi import APIRouter, Depends
from pydantic import BaseModel, Field
from typing import List, Optional

from backend.dependencies import (
    get_coordinator_agent,
    get_sim_engine,
)

from models.schemas import AgentRequest
from agents.coordinator import CoordinatorAgent

router = APIRouter()


class ChatRequest(BaseModel):
    message: str
    stream: bool = False


class ChatResponse(BaseModel):
    response: str
    context_used: List[str] = Field(default_factory=list)



@router.post("/", response_model=ChatResponse)
async def chat_with_ai(
    request: ChatRequest,
    coordinator: CoordinatorAgent = Depends(get_coordinator_agent),
):
    simulation = get_sim_engine()

    state = simulation.get_state()

    telemetry = {
        **state["telemetry"],
        "venue": "MetLife Stadium",
        "event": "FIFA World Cup 2026",
        "match_phase": "Pre-Kickoff",
        "minutes_to_kickoff": 18,
        "fan_zones": {
            "north": "Normal",
            "south": "Busy",
            "east": "Normal",
            "west": "Busy",
        },
        "iot": {
            "cctv": "Operational",
            "ai_cameras": "Active",
            "drone_feed": "Online",
            "turnstiles": "Operational",
        },
    }

    agent_request = AgentRequest(
        query=request.message,
        telemetry=telemetry,
        history=[]
    )

    result = await coordinator.process(agent_request)

    report = f"""
🏟️ STADIUMOPS AI COMMAND CENTER

🚨 COMMAND PRIORITY: {getattr(result, "priority", "MEDIUM")}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📋 SITUATION ASSESSMENT

{getattr(result, "analysis", "No analysis available.")}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⚠ OPERATIONAL COMMANDS
"""

    recommendations = getattr(result, "recommendations", [])

    if recommendations:
        for idx, rec in enumerate(recommendations, start=1):
            report += f"""

{idx}. {rec.action}

   📍 Area: {rec.target_zone}

   ⚠ Priority: {rec.priority}

   Reason:
   {rec.justification}
"""
    else:
        report += "\nNo operational recommendations generated.\n"

    report += """

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎯 NEXT ACTIONS

"""

    next_actions = getattr(result, "next_actions", [])

    if next_actions:
        for action in next_actions:
            report += f"• {action}\n"
    else:
        report += "• Continue monitoring telemetry.\n"

    alerts = getattr(result, "alerts", [])

    if alerts:
        report += """

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🚨 ACTIVE ALERTS

"""

        for alert in alerts:
            report += f"""
• [{alert.level}]
  {alert.message}

  Time: {alert.timestamp}
"""

    confidence = getattr(result, "confidence", None)

    if confidence:
        score = confidence.score * 100
        reasoning = confidence.reasoning
    else:
        score = 0
        reasoning = "Confidence unavailable."

    report += f"""

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 AI CONFIDENCE

Score: {score:.0f}%

Reason:
{reasoning}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📡 LIVE TELEMETRY

Attendance:
{telemetry["attendance"]:,}/{telemetry["max_capacity"]:,}

Average Queue:
{telemetry["avg_queue_time"]} min

Parking Occupancy:
{telemetry["parking"]}%

Weather:
{telemetry["weather"]["condition"]}

Temperature:
{telemetry["weather"]["temp"]}°C

Match Phase:
{telemetry["match_phase"]}

Kickoff:
{telemetry["minutes_to_kickoff"]} minutes

AI Cameras:
{telemetry["iot"]["ai_cameras"]}

CCTV:
{telemetry["iot"]["cctv"]}

Drone Feed:
{telemetry["iot"]["drone_feed"]}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🏟️ Venue: {telemetry["venue"]}
🏆 Event: {telemetry["event"]}
🤖 Generated by StadiumOps AI Multi-Agent Command Center
"""

    return ChatResponse(
        response=report,
        context_used=[
            "simulation_engine",
            "multi_agent_reasoning",
            "stadium_telemetry",
            "coordinator_agent",
            "iot_sensor_network",
            "cctv_analytics",
        ],
    )